### ISSUE TITLE
[minor] HTML "preview" link

### ISSUE THREAD

**Issue by danielweck** [w3c/bdcoma-cg#1]
In the past I've had (temporary) access problems with `http://htmlpreview.github.io` (which is a client side CORS proxy fetcher).

So, instead of this URL:

http://htmlpreview.github.io/?https://github.com/w3c/bdcoma-cg/blob/master/BD%20Comics%20Manga%20Community%20Group%20Charter.htm

...could you please consider using one of the commonly-accepted alternatives to (now-defunct) RawGit, such as:

https://raw.githack.com/w3c/bdcoma-cg/master/BD%20Comics%20Manga%20Community%20Group%20Charter.htm

...or:

https://cdn.staticaly.com/gh/w3c/bdcoma-cg/master/BD%20Comics%20Manga%20Community%20Group%20Charter.htm

...or:

https://gitcdn.link/repo/w3c/bdcoma-cg/master/BD%20Comics%20Manga%20Community%20Group%20Charter.htm

...or:

https://combinatronics.com/w3c/bdcoma-cg/master/BD%20Comics%20Manga%20Community%20Group%20Charter.htm

?

**Comment by llemeurfr** [comment]
no problem. I've updated the readme to use githack. 

Laurent

**Comment by danielweck** [comment]
Thank you :)
I've added a couple more links just in case the other ones fail / cease to operate in the future.
